// <auto-generated />
namespace CarRental.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class UserEntity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserEntity));
        
        string IMigrationMetadata.Id
        {
            get { return "201911081702062_UserEntity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
